# Generated by Django 5.2.17 on 2026-09-02 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def refuse_issuance_evidence_rollback(apps, schema_editor):
    DemoIssuanceResult = apps.get_model("demo", "DemoIssuanceResult")
    if DemoIssuanceResult.objects.using(
        schema_editor.connection.alias
    ).exists():
        raise RuntimeError(
            "Cannot reverse demo.0001 while issuance result evidence exists; "
            "preserve or export issuance result evidence before retrying rollback."
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0005_alter_signingkey_options'),
        ('documents', '0005_alter_document_options_alter_issuance_options_and_more'),
        ('jobs', '0002_job_job_kind_stable_job_job_status_stable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoIssuanceResult',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='demo_issuance_result', serialize=False, to='jobs.job')),
                ('attempt', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('owner_token', models.UUIDField(editable=False, unique=True)),
                ('output_object_key', models.CharField(max_length=1024, unique=True)),
                ('output_state', models.CharField(choices=[('reserved', 'Reserved'), ('uploading', 'Uploading'), ('committed', 'Committed'), ('cleanup_required', 'Cleanup required'), ('cleaned', 'Cleaned')], default='reserved', max_length=24)),
                ('algorithm_label', models.CharField(blank=True, max_length=64, null=True)),
                ('candidate_identifier', models.CharField(blank=True, max_length=146, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{146}$')])),
                ('canvas_height', models.PositiveIntegerField(blank=True, null=True)),
                ('canvas_width', models.PositiveIntegerField(blank=True, null=True)),
                ('input_sha256', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter exactly 64 lowercase hexadecimal SHA-256 characters.', regex='^[0-9a-f]{64}$')])),
                ('output_sha256', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter exactly 64 lowercase hexadecimal SHA-256 characters.', regex='^[0-9a-f]{64}$')])),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('cleanup_failures', models.PositiveSmallIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_result', to='documents.issuance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
            ],
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['output_state', 'updated_at'], name='demo_result_cleanup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('output_state__in', ['reserved', 'uploading', 'committed', 'cleanup_required', 'cleaned'])), name='demo_result_state_stable'), models.CheckConstraint(condition=models.Q(('attempt__gte', 0), ('attempt__lte', 2)), name='demo_result_attempt_0_2'), models.CheckConstraint(condition=models.Q(('input_sha256__isnull', True), ('input_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='demo_result_input_sha256'), models.CheckConstraint(condition=models.Q(('output_sha256__isnull', True), ('output_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='demo_result_output_sha256'), models.CheckConstraint(condition=models.Q(models.Q(('output_state', 'committed'), _negated=True), models.Q(('algorithm_label', 'experimental_unreleased_fingerprint_v2'), ('candidate_identifier', '5342463201e7490f80b69ef1a3289afce40ef02989c9a4d89f00b916055cbf1c4c83a97b880000000240380000000000003ff800000000000000000180000000120000000300000003'), ('canvas_height', 2304), ('canvas_width', 1152), ('input_sha256__isnull', False), ('output_sha256__isnull', False), ('page_count__gte', 1), ('page_count__lte', 5), ('processing_ms__isnull', False), ('limitations', ['fingerprint.experimental_unreleased_v2', 'fingerprint.not_gate_g1_evidence', 'evidence.not_proof_of_leak_edit_or_distribution']), ('cleanup_failures', 0), ('safe_error_code__isnull', True)), _connector='OR'), name='demo_result_committed_complete')],
            },
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=refuse_issuance_evidence_rollback,
        ),
    ]
