# Generated by Django 5.2.17 on 2026-09-02 09:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def refuse_verification_evidence_rollback(apps, schema_editor):
    DemoVerificationResult = apps.get_model("demo", "DemoVerificationResult")
    if DemoVerificationResult.objects.using(
        schema_editor.connection.alias
    ).exists():
        raise RuntimeError(
            "Cannot reverse demo.0002 while verification result evidence exists; "
            "preserve or export verification result evidence before retrying rollback."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_signingkey_options'),
        ('demo', '0001_initial'),
        ('documents', '0005_alter_document_options_alter_issuance_options_and_more'),
        ('jobs', '0002_job_job_kind_stable_job_job_status_stable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVerificationResult',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='demo_verification_result', serialize=False, to='jobs.job')),
                ('attempt', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('owner_token', models.UUIDField(editable=False, unique=True)),
                ('result_state', models.CharField(choices=[('reserved', 'Reserved'), ('committed', 'Committed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='reserved', max_length=16)),
                ('input_sha256', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter exactly 64 lowercase hexadecimal SHA-256 characters.', regex='^[0-9a-f]{64}$')])),
                ('result_status', models.CharField(blank=True, choices=[('VERIFIED_INTACT', 'Verified intact'), ('SOURCE_IDENTIFIED_MODIFIED', 'Source identified, modified'), ('PARTIAL_EVIDENCE', 'Partial evidence'), ('NO_WATERMARK', 'No watermark'), ('INVALID_MANIFEST', 'Invalid manifest'), ('PROCESSING_FAILED', 'Processing failed')], max_length=32, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('safe_error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
                ('recovered_issuance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demo_verification_results', to='documents.issuance')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_result', to='documents.verification')),
            ],
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('result_state__in', ['reserved', 'committed', 'failed', 'cancelled'])), name='demo_verify_state_stable'), models.CheckConstraint(condition=models.Q(('attempt__gte', 0), ('attempt__lte', 2)), name='demo_verify_attempt_0_2'), models.CheckConstraint(condition=models.Q(('input_sha256__isnull', True), ('input_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='demo_verify_input_sha256'), models.CheckConstraint(condition=models.Q(('result_status__isnull', True), ('result_status__in', ['VERIFIED_INTACT', 'SOURCE_IDENTIFIED_MODIFIED', 'PARTIAL_EVIDENCE', 'NO_WATERMARK', 'INVALID_MANIFEST', 'PROCESSING_FAILED']), _connector='OR'), name='demo_verify_status_stable')],
            },
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=refuse_verification_evidence_rollback,
        ),
    ]
