# Generated by Django 5.2.17 on 2026-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_signingkey_options'),
        ('demo', '0003_raise_committed_page_count'),
        ('documents', '0005_alter_document_options_alter_issuance_options_and_more'),
        ('jobs', '0002_job_job_kind_stable_job_job_status_stable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='demoissuanceresult',
            name='demo_result_committed_complete',
        ),
        migrations.AddConstraint(
            model_name='demoissuanceresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('output_state', 'committed'), _negated=True), models.Q(('algorithm_label', 'experimental_unreleased_fingerprint_v2'), ('candidate_identifier__in', ('5342463201e7490f80b69ef1a3289afce40ef02989c9a4d89f00b916055cbf1c4c83a97b88000000024040000000000000400000000000000000000180000000120000000300000003', '5342463201e7490f80b69ef1a3289afce40ef02989c9a4d89f00b916055cbf1c4c83a97b880000000240380000000000003ff800000000000000000180000000120000000300000003')), ('canvas_height', 2304), ('canvas_width', 1152), ('input_sha256__isnull', False), ('output_sha256__isnull', False), ('page_count__gte', 1), ('page_count__lte', 50), ('processing_ms__isnull', False), ('limitations', ['fingerprint.experimental_unreleased_v2', 'fingerprint.not_gate_g1_evidence', 'evidence.not_proof_of_leak_edit_or_distribution']), ('cleanup_failures', 0), ('safe_error_code__isnull', True)), _connector='OR'), name='demo_result_committed_complete'),
        ),
    ]
