# Generated by Django 5.2.17 on 2026-08-29 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('issuance', 'Issuance'), ('verification', 'Verification')], max_length=16)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter exactly 64 lowercase hexadecimal SHA-256 characters.', regex='^[0-9a-f]{64}$')])),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('expires_at', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'purpose', 'created_at'], name='upload_org_purpose_idx'), models.Index(fields=['finalized_at', 'expires_at'], name='upload_retention_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sha256__isnull', True), ('sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='upload_sha256_canonical')],
            },
        ),
    ]
