# Generated by Django 5.2.17 on 2026-08-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_cleanup_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadrequest',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
    ]
