# Generated by Django 5.2.17 on 2026-09-12 10:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_signingkey_options'),
        ('uploads', '0010_reconciliation_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadrequest',
            name='upload_size_legacy_null_or_bounded',
        ),
        migrations.AlterField(
            model_name='uploadrequest',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(104857600)]),
        ),
        migrations.AddConstraint(
            model_name='uploadrequest',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__isnull', True), models.Q(('size_bytes__gte', 1), ('size_bytes__lte', 104857600)), _connector='OR'), name='upload_size_legacy_null_or_bounded'),
        ),
    ]
