# Generated by Django 5.2.17 on 2026-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_raise_upload_size_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='source_filename',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
