# Generated by Django 5.2.17 on 2026-09-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0012_add_source_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='source_content_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
