# Generated by Django 5.2.17 on 2026-08-29 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=120)),
                ('correlation_id', models.UUIDField()),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='audit_org_created_idx'), models.Index(fields=['organization', 'action', 'created_at'], name='audit_org_action_idx'), models.Index(fields=['correlation_id'], name='audit_correlation_idx')],
            },
        ),
    ]
