# Generated by Django 5.2.17 on 2026-08-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
    ]
