# Generated by Django 5.2.17 on 2026-08-29 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('topic', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['published_at', 'created_at'], name='outbox_pending_idx'), models.Index(fields=['organization', 'created_at'], name='outbox_org_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempt__gte', 0), ('attempt__lte', 2)), name='outbox_attempt_0_2'), models.UniqueConstraint(fields=('job', 'attempt'), name='outbox_job_attempt_uniq')],
            },
        ),
    ]
