# Generated by Django 5.2.17 on 2026-08-29 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_key', models.CharField(max_length=1024, unique=True)),
                ('source_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter exactly 64 lowercase hexadecimal SHA-256 characters.', regex='^[0-9a-f]{64}$')])),
                ('page_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
                ('upload_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='uploads.uploadrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_object_key', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('output_sha256', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter exactly 64 lowercase hexadecimal SHA-256 characters.', regex='^[0-9a-f]{64}$')])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='access.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_payload', models.TextField()),
                ('internal_signature_envelope', models.JSONField()),
                ('public_payload', models.TextField()),
                ('public_signature_envelope', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manifest', to='documents.issuance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
                ('signing_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='access.signingkey')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('VERIFIED_INTACT', 'Verified intact'), ('SOURCE_IDENTIFIED_MODIFIED', 'Source identified, modified'), ('PARTIAL_EVIDENCE', 'Partial evidence'), ('NO_WATERMARK', 'No watermark'), ('INVALID_MANIFEST', 'Invalid manifest'), ('PROCESSING_FAILED', 'Processing failed')], max_length=32, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
                ('recovered_issuance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='documents.issuance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications_requested', to=settings.AUTH_USER_MODEL)),
                ('upload_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='uploads.uploadrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'created_at'], name='document_org_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('source_sha256__regex', '^[0-9a-f]{64}$')), name='document_sha256_canonical'),
        ),
        migrations.AddIndex(
            model_name='issuance',
            index=models.Index(fields=['organization', 'issued_at'], name='issuance_org_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='issuance',
            index=models.Index(fields=['organization', 'recipient'], name='issuance_org_recipient_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuance',
            constraint=models.CheckConstraint(condition=models.Q(('output_sha256__isnull', True), ('output_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='issuance_sha256_canonical'),
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['organization', 'created_at'], name='manifest_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['organization', 'created_at'], name='verify_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['organization', 'status'], name='verify_org_status_idx'),
        ),
    ]
