# Generated by Django 5.2.17 on 2026-08-29 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_user_user_role_stable'),
        ('documents', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(('status__isnull', True), ('status__in', ['VERIFIED_INTACT', 'SOURCE_IDENTIFIED_MODIFIED', 'PARTIAL_EVIDENCE', 'NO_WATERMARK', 'INVALID_MANIFEST', 'PROCESSING_FAILED']), _connector='OR'), name='verification_status_stable'),
        ),
    ]
