# Generated by Django 5.2.17 on 2026-08-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_issuance_output_deletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='issuance',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='manifest',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
    ]
