# Generated by Django 5.2.17 on 2026-08-29 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('issuance', 'Issuance'), ('verification', 'Verification')], max_length=24)),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('processing', 'Processing'), ('retryable_failed', 'Retryable failed'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dead_lettered', 'Dead lettered'), ('cancelled', 'Cancelled')], default='created', max_length=32)),
                ('attempt', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('deadline_at', models.DateTimeField()),
                ('correlation_id', models.UUIDField()),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('safe_error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='documents.issuance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='documents.verification')),
            ],
        ),
        migrations.CreateModel(
            name='JobResultReceipt',
            fields=[
                ('message_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_receipts', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='access.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='job_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'deadline_at'], name='job_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['correlation_id'], name='job_correlation_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 0), ('attempt__lte', 2)), name='job_attempt_0_2'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issuance__isnull', False), ('kind', 'issuance'), ('verification__isnull', True)), models.Q(('issuance__isnull', True), ('kind', 'verification'), ('verification__isnull', False)), _connector='OR'), name='job_kind_target_match'),
        ),
        migrations.AddIndex(
            model_name='jobresultreceipt',
            index=models.Index(fields=['organization', 'received_at'], name='receipt_org_received_idx'),
        ),
    ]
