# Generated by Django 5.2.17 on 2026-08-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_user_user_role_stable'),
        ('documents', '0002_verification_verification_status_stable'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['issuance', 'verification'])), name='job_kind_stable'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'queued', 'processing', 'retryable_failed', 'succeeded', 'failed', 'dead_lettered', 'cancelled'])), name='job_status_stable'),
        ),
    ]
