# Generated by Django 5.2.17 on 2026-08-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['administrator', 'issuer', 'verifier', 'auditor'])), name='user_role_stable'),
        ),
    ]
