# Generated by Django 5.2.17 on 2026-08-29 07:30

import splitbind.access.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_user_user_role_stable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', splitbind.access.models.UserManager()),
            ],
        ),
    ]
