# Generated by Django 5.2.17 on 2026-08-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_signing_key_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signingkey',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
    ]
